INSERT INTO MY_USERS(USERNAME,PASSWORD, ENABLED)
values ('user', 'pass', true);
INSERT INTO MY_USERS(USERNAME,PASSWORD, ENABLED)
values ('admin', 'pass', true);
INSERT INTO MY_USERS(USERNAME,PASSWORD, ENABLED)
values ('atanu1', 'pass', true);
INSERT INTO MY_USERS(USERNAME,PASSWORD, ENABLED)
values ('atanu2', 'pass', true);



INSERT INTO MY_AUTHORITIES(USERNAME,AUTHORITY)
values ('user', 'USER');

INSERT INTO MY_AUTHORITIES(USERNAME,AUTHORITY)
values ('admin', 'ADMIN');

INSERT INTO MY_AUTHORITIES(USERNAME,AUTHORITY)
values ('atanu1', 'ADMIN');
INSERT INTO MY_AUTHORITIES(USERNAME,AUTHORITY)
values ('atanu2', 'USER');